MastanSayyad/Visual-Sort

.vscode/settings.json, index.html
=> Changed Website Title From Visual Sort to Sort It

css/style.css, index.html
Enhance the footer to close issue #5
=> fix: footer ui

index.html
=> Add About Us Link in Navbar

index.html
Issue Fixes #4
Added **About us** section 
Linked it to **navbar** and **footer**
=> Add About us section to the home page

index.html
Issue Fixes #22 
Added **Quick sort** algorithm with visualization.
Added a quick sort card in the slider.
=> Add Quick sort algorithm

css/style.css, index.html
I have added the icons of social media and also added the the hover and transform property to the links and icons
https://github.com/MastanSayyad/Visual-Sort/assets/113382989/a2be70f1-f8be-4dfe-9af0-796c0533b9e7
=> Footer enhancement

css/style.css, index.html, js/main.js
Hey I have Added FAQ Section
https://github.com/MastanSayyad/Visual-Sort/assets/114497044/f334edf1-4173-4f3e-98fc-99a67514b28b
=> FAQ Added 

index.html
Fix the subscribe btn ui (minor issue)
=> fix: minor subscribe btn ui

css/style.css, index.html
1. Added a responsive navbar with hover animation
2. Added necessary sections
issue#2 
email- mehakmattoo7@gmail.com
=> Navbar Changes

index.html, style.css
Removed the excessive whitespace from footer section, added hover effect with scale 1.2 to the links and also linked the social media (github and linkedin) links.
=> made changes in Index.html and Style.css

index.html
Adding a dropdown in navbar for sorting visualizers
issue#46 and email-mehakmattoo7@gmail.com
=> Dropdown addition

index.html, style.css
=> Enhancing Footer Section

css/style.css, index.html
Made review section more responsive by adding media queries
issue closes #64 
email- mehakmattoo7@gmail.com
=> Review section bug

chatbot.html, index.html, main.js, style.css
Email :- 1ammar.yaser@gmail.com
Isse #26 
We propose the addition of an AI-powered chatbot to our study website to enhance user engagement, provide instant support, and improve overall user experience. This chatbot will assist users by answering common questions, guiding them through the site, offering study tips, and potentially integrating with existing educational resources.
Objectives:
1.Instant User Support
2.Enhanced User Experience
3.Resource Integration
https://github.com/MastanSayyad/Visual-Sort/assets/140265777/3bccee48-f60c-42a8-b4b5-080bdce6dc2f
=> Add AI Chatbot Feature to Enhance User Engagement on Study Website

about.css, index.html
Issue Fixes #59 
- Enhanced About us page with suitable font color and Box-shadow.
- Improved the Heading style of "Sorting Visualizers" as desired.
- Added transitions to About us and Features sections
=> Enhancement of About Us page

css/style.css, index.html
fixed review section
Email id: akshatpandey26.2004@gmail.com
label: medium
=> fixed review section

css/style.css, index.html, style.css
Made a new responsive hero section with a corresponding img and buttons for navigation.
Issue closes #86
=> Hero section

visual.html
added an algo button in visualisation for understanding sorting better
#75 
Issue fixes: #75
=> algorithm button added

index.html
fIxed copyright year_bug and edited the text as specified 
Issue fixes: #105 
VSOC email - meetofficialhere@gmail.com
=> Fix : bug Copyright year

.vscode/settings.json, index.html, login.html, signup.html
=> updated the login signup and hero section

Algorithm/Insertionsort.html, Algorithm/Insertionsort.js
Email: akshatpandey26.2004@gmail.com
Label: Bonus
=> Insertion sort

index.html
=> had undo changes and add an arrow

Terms.html, terms.css
@MastanSayyad 
Successfully changed terms & condition page.
Issue fixes: #138 
before 
After
=> terms&condition successfully changed

licensing.html, privacy-policy.html
Hey @MastanSayyad 
- issue closes #140 
I have enhanced the user interface of the Privacy Policy and Licensing pages to improve readability and align the design with the overall website theme.
- Privacy Policy
-  Licensing
Please review and merge it.
=> Enhanced UI for Privacy Policy and Licensing Pages

contributors.html
Hey @MastanSayyad 
issue closes #153 
I have added the custom vertical scrollbar and scroll-progress bar in the contributors page.
=> ✔️Added Custom Scrollbar + Scrollprogress in Contributors page

contributors.html
hi @MastanSayyad 
issue closes #155 
i have added the smooth diagonal transition effect matching the theme.
=> ✔️Added Diagonal-Hovering Effect to Each Card!
